BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-cvwsoc"
BBFILE_PATTERN_meta-cvwsoc = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-cvwsoc = "20"

LAYERDEPENDS_meta-cvwsoc = "core"
LAYERSERIES_COMPAT_meta-cvwsoc = "whinlatter"

INHERIT += "rm_work"
RM_WORK_EXCLUDE += "u-boot-cvwsoc cvwsoc-image-minimal"
