#@TYPE: Machine
#@NAME: CVWSoC with CVA6 SoC for Genesys 2
#@SOC: Core-V Wally SoC
#@DESCRIPTION: Machine configuration for the CVW SoC on Nexys A7

require cva6soc64.inc

CVWSOC_BOARDNAME = "genesys2"
# FIXME
MACHINEOVERRIDES:append = ":cvwsoc-genesys2"

UBOOT_MACHINE = "openhwgroup_cvwsoc_defconfig"
