#@TYPE: Machine
#@NAME: CVWSoC with CVA32A6 SoC for Genesys 2
#@SOC: Core-V Wally SoC
#@DESCRIPTION: Machine configuration for the CVW SoC with CV32A6 on Genesys 2

require cva6soc32.inc

#CVWSOC_BOARDNAME = "genesys2rv32"
CVWSOC_BOARDNAME = "genesys2"
# FIXME
MACHINEOVERRIDES:append = ":cvwsoc-genesys2rv32"

UBOOT_MACHINE = "openhwgroup_cvwsoc_rv32_defconfig"
