#@TYPE: Machine
#@NAME: CVWSoC with CV32A6 for Nexys A7
#@SOC: Core-V Wally SoC
#@DESCRIPTION: Machine configuration for the CVWSoC with CV32A6 with Nexys A7

require cva6soc32.inc

#CVWSOC_BOARDNAME = "nexysa7rv32"
CVWSOC_BOARDNAME = "nexysa7"
# FIXME
MACHINEOVERRIDES:append = ":cvwsoc-nexysa7rv32"

UBOOT_MACHINE = "openhwgroup_cvwsoc_rv32_defconfig"
