#@TYPE: Machine
#@NAME: Core-V Wally SoC for Nexys A7
#@SOC: Core-V Wally SoC
#@DESCRIPTION: Machine configuration for the CVW SoC on Nexys A7

require cvwsoc64.inc

CVWSOC_BOARDNAME = "nexysa7"

UBOOT_MACHINE = "openhwgroup_cvwsoc_defconfig"
UBOOT_DTB_BINARY = "cvwsoc-nexysa7.dtb"
