#@TYPE: Machine
#@NAME: Core-V Wally SoC with Vexriscv CPU for Genesys 2 
#@SOC: Core-V Wally SoC
#@DESCRIPTION: Machine configuration for the CVW SoC with Vexriscv on Nexys A7

require vexriscvsoc32.inc
#require cvwsocvirt.inc

#CVWSOC_BOARDNAME = "genesys2rv32"
CVWSOC_BOARDNAME = "genesys2"
# FIXME
MACHINEOVERRIDES:append = ":cvwsoc-genesys2rv32"

# Use generic cvwsoc config
UBOOT_MACHINE = "openhwgroup_cvwsoc_rv32_defconfig"