#@TYPE: Machine
#@NAME: Core-V Wally SoC for Nexys A7
#@SOC: Core-V Wally SoC
#@DESCRIPTION: Machine configuration for the CVW SoC on Nexys A7

require vexriscvsoc32.inc
require cvwsocvirt.inc

#CVWSOC_BOARDNAME = "virt32"
CVWSOC_BOARDNAME = "virt"
# FIXME
MACHINEOVERRIDES:append = ":cvwsoc-virt32"

# Use generic cvwsoc config
UBOOT_MACHINE = "openhwgroup_cvwsoc_rv32_defconfig"