#@TYPE: Machine
#@NAME: Core-V Wally SoC with Vexriscv CPU for Nexys A7
#@SOC: Core-V Wally SoC
#@DESCRIPTION: Machine configuration for the CVW SoC with Vexriscv on Nexys A7

require vexriscvsoc32.inc
#require cvwsocvirt.inc

#CVWSOC_BOARDNAME = "nexysa7rv32"
CVWSOC_BOARDNAME = "nexysa7"
# FIXME
MACHINEOVERRIDES:append = ":cvwsoc-nexysa7rv32"

# Use generic cvwsoc config
UBOOT_MACHINE = "openhwgroup_cvwsoc_rv32_defconfig"