

require conf/distro/poky.conf


DISTRO = "distro-cvwsoc-basic"
DISTRO_NAME = "CVWSoC basic distro"

DISTRO_FEATURES:remove = "bluetooth debuginfod pcmcia wifi pci 3g nfc x11 seccomp opengl ptest wayland vulkan pulseaudio "
DISTRO_FEATURES:append = " fbcon "

# Settings for building JFFS2 of arbitrary size and supported by the Kernel
IMAGE_FSTYPES:append = " jffs2"
# Size must be aligned to the JFFS2 erase block: 8 KiB.
IMAGE_ROOTFS_ALIGNMENT = "8"
JFFS2_ENDIANNESS = "-l"
JFFS2_ERASEBLOCK = "0x2000"
JFFS2_FREE_SPACE_MIB = "32"
EXTRA_IMAGECMD:jffs2 = "--pad -l --eraseblock=0x2000 --no-cleanmarkers -x zlib -x rtime"
IMAGE_CMD:jffs2:append = "; \
        dd if=/dev/zero bs=1M count=${JFFS2_FREE_SPACE_MIB} status=none | \
        tr '\000' '\377' >> ${IMGDEPLOYDIR}/${IMAGE_NAME}.jffs2"
