require conf/distro/poky.conf

DISTRO = "distro-cvwsoc-tiny"
DISTRO_NAME = "CVWSoC tiny distro"

DISTRO_FEATURES:remove = "bluetooth debuginfod pcmcia wifi pci 3g nfc x11 seccomp opengl ptest wayland vulkan pulseaudio "
DISTRO_FEATURES:append = " tiny"
# DISTRO_FEATURES = "tiny"
# DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit gobject-introspection-data ldconfig"

KERNEL_IMAGETYPE = "Image"
IMAGE_FSTYPES:append = " cpio ext2 jffs2"
EXTRA_IMAGECMD:jffs2 = "--pad=0x400000 -l --eraseblock=0x2000 --no-cleanmarkers -x zlib -x rtime"
# 4MB should be enough for now
IMAGE_ROOTFS_SIZE = "4096"
