

require conf/distro/poky.conf


DISTRO = "distro-cvwsoc-basic"
DISTRO_NAME = "CVWSoC basic distro"

DISTRO_FEATURES:remove = "bluetooth debuginfod pcmcia wifi pci 3g nfc x11 seccomp opengl ptest wayland vulkan pulseaudio "
DISTRO_FEATURES:append = " fbcon"
